set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports s]
set_property PACKAGE_PIN U7 [get_ports a]
set_property PACKAGE_PIN W5 [get_ports b]
set_property PACKAGE_PIN W6 [get_ports c]
set_property PACKAGE_PIN W7 [get_ports s]
